name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  deploy:
    environment: production
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: dist/
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::513002791029:role/wavebuto-cicd
      - run: aws s3 sync dist/wavebuto/browser/ s3://calmayourdrama-wavebuto/ --delete